const PDFDocument = require("pdfkit");

const generateFeeReceipt = (res, data) => {
  const doc = new PDFDocument({ margin: 40 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=Sem_Fee_Receipt.pdf"
  );

  doc.pipe(res);

  // ===== TITLE =====
  doc
    .fontSize(18)
    .text("Sem Fee Submission Receipt", { align: "center" })
    .moveDown(1.5);

  // ===============================
  // TRANSACTION DETAILS
  // ===============================
  doc.fontSize(14).text("TRANSACTION DETAILS", { underline: true });
  doc.moveDown(0.5);

  doc.fontSize(12);
  doc.text(`Application Number: ${data.applicationNumber}`);
  doc.text(`Payment Status: ${data.paymentStatus}`);
  doc.text(`Payment Mode: ${data.paymentMode}`);
  doc.text(`Transaction Id: ${data.transactionId}`);
  doc.text(`Channel Id: ${data.channelId}`);
  doc.text(`Portal Fee: ₹${data.portalFee}`);
  doc.text(`Sem Fees: ₹${data.semFees}`);
  doc.text(`Late Fee: ₹${data.lateFee}`);
  doc.text(`Total Fee: ₹${data.totalFee}`);
  doc.moveDown(1.5);

  // ===============================
  // EDUCATIONAL DETAILS
  // ===============================
  doc.fontSize(14).text("EDUCATIONAL DETAILS", { underline: true });
  doc.moveDown(0.5);

  doc.fontSize(12);
  doc.text(`Enrollment No: ${data.enrollmentNumber}`);
  doc.text(`Semester: ${data.semester}`);
  doc.text(`Year Term: ${data.yearTerm}`);
  doc.text(`College Name: ${data.collegeName}`);
  doc.text(`Course Name: ${data.course}`);
  doc.text(`Branch Name: ${data.branch}`);
  doc.moveDown(1.5);

  // ===============================
  // HEADER WISE FEE DETAILS
  // ===============================
  doc.fontSize(14).text("Header Wise Fee Details", { underline: true });
  doc.moveDown(0.5);

  doc.fontSize(12);
  doc.text(`Academic Fee: ₹${data.tuitionFee}`);
  doc.text(`Development Fee: ₹${data.developmentFee}`);
  doc.text(`Exam Fees: ₹${data.examFee}`);
  doc.text(`University Fees: ₹${data.universityFee}`);
  doc.text(`Caution Money: ₹${data.cautionMoney}`);
  doc.text(`Alumni Fees: ₹${data.alumniFee}`);
  doc.moveDown(1.5);

  // ===============================
  // STUDENT DETAILS
  // ===============================
  doc.fontSize(14).text("STUDENT DETAILS", { underline: true });
  doc.moveDown(0.5);

  doc.fontSize(12);
  doc.text(`Full Name: ${data.name}`);
  doc.text(`Father's Name: ${data.fatherName}`);
  doc.text(`Mother's Name: ${data.motherName}`);
  doc.moveDown(2);

  doc.text("Generated by College Portal", { align: "center" });

  doc.end();
};

module.exports = { generateFeeReceipt };
